<a href="https://colab.research.google.com/github/Ayesha765/pwAssign/blob/main/Assignment_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **THEORETICAL QUESTIONS**


Q.1 Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

ANS) NumPy is a powerful library in Python designed for efficient numerical operations, particularly in scientific computing and data analysis. Its primary purpose is to provide support for handling large datasets and performing mathematical computations with arrays and matrices, offering functionality that enhances Python's native capabilities.

Purpose of NumPy:
1. Array Handling: Provides the ndarray, a fast and flexible multi-dimensional
array object for storing data.
2. Mathematical Operations: Supplies a wide array of mathematical functions (e.g., linear algebra, statistical operations, Fourier transforms) that operate on arrays and matrices.
3. Data Manipulation: Enables easy reshaping, slicing, and broadcasting of arrays, allowing complex manipulations with concise syntax.
4. Interfacing: Acts as a foundation for other libraries like SciPy and pandas, providing a common data structure for scientific computing.

Advantages of NumPy:
1. Speed: NumPy arrays are implemented in C, making operations on them significantly faster compared to Python lists, especially for large datasets.
2. NumPy arrays require less memory than Python lists by storing data in a compact, contiguous block of memory.
3. Vectorization: Enables operations to be applied element-wise to entire arrays without the need for explicit loops, improving both readability and performance.
4. Broad Functionality: Offers a rich ecosystem for numerical computation, including tools for random number generation, matrix operations, and mathematical modeling.
5. Interoperability: Can easily interface with data from other languages (e.g., C, C++, and Fortran) and supports efficient integration with other Python libraries.

NumPy's capabilities significantly enhance Python's capabilities for numerical operations by:
1. Providing efficient data structures for handling large numerical datasets
2. Offering a comprehensive set of functions for mathematical operations, linear algebra, and other numerical tasks
3. Integrating seamlessly with other scientific Python libraries
4. Improving memory efficiency and performance
5. Supporting a wide range of applications
6. Benefiting from a large and active community



Q.2 Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

ANS) In NumPy, both np.mean() and np.average() are used to calculate the average of an array, but there are key differences between them in terms of functionality and use cases. Here’s a comparison and explanation of when to use one over the other -
1. Basic Functionality -
   * np.mean(): This function computes the arithmetic mean (or simple average) of the elements in an array.
  * np.average(): By default, this function also computes the arithmetic mean, but it allows you to include weights, which means you can compute a weighted average.
2.  Weights Parameter -
 *  np.mean(): Does not support weights. It calculates a simple average without considering any importance or weight of individual
       elements.
  * np.average(): Supports a weights parameter that allows you to assign different weights to elements, making it ideal for calculating weighted averages.
3. Return Value -
      * np.mean(): Returns a single scalar value representing the arithmetic mean of all elements.
      * np.average(): Also returns a scalar when computing the average. However, if you provide weights and specify returned=True, it will
       return a tuple containing the average and the sum of the weights.
4. Performance -
      * np.mean(): Generally faster when you only need a simple average since it doesn’t involve the additional overhead of processing weights.
      * np.average(): Slightly slower due to the flexibility it offers with weights, even if weights are not used.
5. Use Cases -
      Use np.mean() when:
       * You want to compute a simple arithmetic mean of an array.
       * You do not need to consider the importance or weight of individual elements.
       * You are looking for a fast, straightforward average calculation.
      Use np.average() when:
       * You need to calculate a weighted average where some elements contribute more to the result than others.
       * You want to retrieve both the average and the sum of the weights using the returned=True option

In [ ]:
# example
import numpy as np

data = np.array([1, 2, 3, 4])

# Unweighted mean
mean = np.mean(data)
print("Mean:", mean)  # Output: 2.5

data = [1, 2, 3, 4]
weights = [1, 2, 3, 4]  # These weights mean '4' is more important
avg = np.average(data, weights=weights)
print("avarage:",avg)

Mean: 2.5
avarage: 3.0


Q. 3 Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

ANS) In NumPy, arrays can be reversed along different axes using several methods. Below are common techniques to reverse a NumPy array along different axes:

1. Using Slicing : ([::-1])


In [ ]:
# 1D Array : In a 1D array, you can reverse the entire array using slicing.

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
rev_arr = arr[::-1]
print(rev_arr)  # Output: [5 4 3 2 1]

print("================")

# 2D Array : For a 2D array, you can reverse it along a specific axis (rows or columns) by slicing the appropriate axis.

# Reverse rows (axis 0):

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_rows = arr_2d[::-1, :]
print(reversed_rows)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]

print("================")
# Reverse columns (axis 1):

reversed_columns = arr_2d[:, ::-1]
print(reversed_columns)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]


[5 4 3 2 1]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


2. Using np.flip():

np.flip() reverses an array along a specified axis. It is a more flexible method than slicing, allowing you to specify the axis explicitly.



In [ ]:
# 1D Array : By default, np.flip() flips the array along its only axis.

flipped_arr_1d = np.flip(arr)
print(flipped_arr_1d)  # Output: [5 4 3 2 1]

print("==============")

# 2D Array : For 2D arrays, you can flip along different axes:

# Flip along rows (axis 0):

flipped_rows = np.flip(arr_2d, axis=0)
print(flipped_rows)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]
print("==============")

# Flip along columns (axis 1):
flipped_columns = np.flip(arr_2d, axis=1)
print(flipped_columns)

# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]


[5 4 3 2 1]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


3. Using np.fliplr() and np.flipud()

These functions are specific to 2D arrays and higher dimensions:

np.fliplr(): Flips the array left to right (i.e., along columns).

np.flipud(): Flips the array upside down (i.e., along rows).



In [ ]:
flip_lr = np.fliplr(arr_2d)

flip_ud = np.flipud(arr_2d)



flip_lr , flip_ud


# Output: flip_lr
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]

# Output: flip_ud
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]


(array([[3, 2, 1],
        [6, 5, 4],
        [9, 8, 7]]),
 array([[7, 8, 9],
        [4, 5, 6],
        [1, 2, 3]]))

Q. 4 How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

ANS)Importance of Data Types in Memory Management and Performance

    1. Memory Management:
      * NumPy arrays are stored as contiguous blocks of memory, which makes accessing elements more efficient than lists. Each element in a NumPy array has a fixed size, determined by its data type.
      * Using appropriate data types reduces memory consumption. For instance storing integers as int8 (8-bit integers) uses less memory than int64 (64-bit integers). Choosing the right data type for your data can significantly reduce the memory footprint of large arrays.

    2. Performance:
       * Data types affect computational performance. Smaller data types (e.g., float32, int16) can be processed faster than larger types(e.g., float64, int64) because they require less memory bandwidth and cache usage.
       * NumPy operations are optimized to run efficiently on fixed-size data types, leveraging CPU vectorization (SIMD operations) for performance improvements.    

    3. Precision:
       * Data types also impact the precision of computations. For example, float32 offers less precision than float64. Depending on theRE requirements, you should select a data type that offers sufficient precision without wasting resources.   

In [ ]:
#To determine the data type of elements in a NumPy array, we use the dtype attribute.
#checking the data type of elements in a NumPy array
arr = np.array([1, 2, 3, 4])
print(arr.dtype)


#In the next example arr_int8 Uses 1 byte per element, arr_int64 Uses 8 bytes per element

arr_int8 = np.array([1, 2, 3], dtype=np.int8)
arr_int64 = np.array([1, 2, 3], dtype=np.int64)
print(arr_int8.nbytes)
print(arr_int64.nbytes)

int64
3
24


Q. 5 Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

ANS)In NumPy, an ndarray (n-dimensional array) is a powerful data structure that holds elements of the same type in a grid-like structure. It can represent multi-dimensional arrays (like 1D, 2D, or even higher dimensions).



In [ ]:
import numpy as np

# 1D ndarray (array)
arr_1d = np.array([1, 2, 3, 4])

# 2D ndarray (matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# printing the ndarray
arr_1d , arr_2d


(array([1, 2, 3, 4]),
 array([[1, 2, 3],
        [4, 5, 6]]))

Key Features of ndarray :

1. Homogeneity: All elements within an ndarray must be of the same data type (e.g., int, float, bool). This ensures efficient memory management and optimized operations.
2. N-dimensional: ndarray can have multiple dimensions (1D, 2D, 3D, etc.), allowing you to represent complex data structures like matrices, tensors, etc.
 * 1D Array (Vector): np.array([1, 2, 3])
 * 2D Array (Matrix): np.array([[1, 2], [3, 4]])
 * 3D Array (Tensor): np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
3. Fixed Size: Once created, the size of an ndarray cannot be changed (though you can create a new one with a different size).
4. Fast Operations: NumPy provides vectorized operations, meaning you can perform element-wise operations on arrays much faster than Python loops.
5. Memory Efficient: NumPy arrays use less memory than Python lists because they store elements of the same type in a contiguous block of memory.
6. Broadcasting: NumPy allows operations on arrays of different shapes, automatically adjusting the shapes when possible (broadcasting). This is very useful for mathematical operations.

Differences from Standard Python Lists:
1. Homogeneity: Unlike Python lists, which can contain elements of different data types, ndarrays require all elements to be of the same type.
2. Performance: NumPy ndarrays are generally much faster than Python lists for numerical operations due to their optimized implementation and vectorized nature.
3. Fixed Size: Python lists are dynamic and can be resized on the fly, while ndarrays have a fixed size.
4. Memory Efficiency: ndarrays are typically more memory-efficient than Python lists, especially for large arrays.
5. Specialized Operations: NumPy provides a rich set of functions and operations specifically designed for working with numerical arrays, which are not available for Python lists.


Q. 6 Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

ANS) The performance benefits of NumPy arrays over Python lists for large-scale numerical operations can be summarized as follows:
1.  Memory Efficiency:
   * NumPy Arrays - Store elements in a contiguous block of memory with a fixed data type, making memory usage more efficient.
   * Python Lists - Store references to objects, causing higher memory overhead, especially for large datasets.
2. Speed (Vectorized Operations):
   *  NumPy Arrays - Support vectorized operations, meaning element-wise operations are performed in highly optimized C code, making them much faster.
   *  Python Lists - Require explicit loops for element-wise operations, which are slower due to Python's interpreted nature.
3. Broadcasting:
   *  NumPy Arrays - Allow arithmetic operations between arrays of different shapes without the need for loops, thanks to broadcasting.
   *  Python Lists - Do not support broadcasting, and manual handling (e.g., nested loops) is needed.
4. Built-in Mathematical Functions:
   * NumPy Arrays - Provide many optimized mathematical functions like sum(),mean(), and dot(), which are faster and more efficient.
  * Python Lists - Use slower Python functions or require custom logic for numerical operations.
5. Parallelization and Optimized CPU Use:
  *   NumPy Arrays - Take advantage of hardware-level optimizations such as SIMD (Single Instruction, Multiple Data), which further speeds up large-scale operations.
  *   Python Lists - Do not leverage these optimizations, resulting in slower computations.


In [ ]:
#Memory Efficiency
import numpy as np
import sys

# Python list memory usage
python_list = [1,2,3,4,5]
print("Memory size of Python list:", sys.getsizeof(python_list))

# NumPy array memory usage
numpy_array = np.array([1,2,3,4,5])
print("Memory size of NumPy array:", numpy_array.nbytes)



#Speed and Vectorization
#Element-wise addition

import time

# Using Python list
python_list = list(range(2000000))
start = time.time()
python_result = (x * 2 for x in python_list)
print("Python list time:", time.time() - start)


# Using NumPy array
numpy_array = np.arange(2000000)
start = time.time()
numpy_result = (numpy_array * 2)
print("Numpy array time:", time.time() - start)



Memory size of Python list: 104
Memory size of NumPy array: 40
Python list time: 0.00025725364685058594
Numpy array time: 0.010124444961547852


Q.7 Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

ANS) Comparison of vstack() and hstack() in Numpy :

In NumPy, vstack() and hstack() are functions used to combine arrays along different axes:
  * vstack(): Vertically stacks arrays (along the row axis). It stacks arrays one on top of the other.
  * hstack(): Horizontally stacks arrays (along the column axis). It stacks arrays side-by-side.

Usage :
  * vstack(): Stacks the arrays vertically, turning the 1D arrays into a 2D array where each input array becomes a row.
  * hstack(): Stacks the arrays horizontally, combining them into a single 1D array where elements from each input array are concatenated side by side.


In [ ]:
# example of both hstack() and vstack()

# Creating two 2D array
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Example of vsatck()
result_vstack = np.vstack((arr1, arr2))
print("VERTICAL STCK OF 2D ARRAYS :\n",result_vstack)


result_hstack =np.hstack((arr1,arr2))
print("\n Horizontal stack of :\n",result_hstack)


VERTICAL STCK OF 2D ARRAYS :
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 Horizontal stack of :
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Q. 8 Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

ANS) In NumPy, fliplr() and flipud() are two methods used to flip or reverse the order of elements in a 2D array (or higher-dimensional arrays). They are specifically designed to flip the array along different axes:
1. fliplr() (Flip Left to Right) -
       Function: Flips the array horizontally, reversing the order of columns (left to right).
       Effect: It flips the array along the second axis (axis=1).
       Applicable to: At least 2D arrays. For higher-dimensional arrays, it flips the elements in each 2D subarray along the second axis.
2. flipud() (Flip Up to Down)
       Function: Flips the array vertically, reversing the order of rows (up to down).
       Effect: It flips the array along the first axis (axis=0).
       Applicable to: At least 2D arrays. For higher-dimensional arrays, it flips the elements in each 2D subarray along the first axis.


In [ ]:
# Example of fliplr() and flipud()

import numpy as np

# Creating a 2D array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

# Using fliplr() - Flip array
arr_fliplr = np.fliplr(arr)

# Using flipud() - Flip array
arr_flipud = np.flipud(arr)

# Printing the results
print("Original array:")
print(arr)
#  Output:
# Original array:
# [[1 2 3 4]
#  [5 6 7 8]]

print("\nArray after fliplr:")
print(arr_fliplr)
# output :
# Array after fliplr:
# [[4 3 2 1]
#  [8 7 6 5]]

print("\nArray after flipud:")
print(arr_flipud)
#output :
# Array after flipud:
# [[5 6 7 8]
#  [1 2 3 4]]

Original array:
[[1 2 3 4]
 [5 6 7 8]]

Array after fliplr:
[[4 3 2 1]
 [8 7 6 5]]

Array after flipud:
[[5 6 7 8]
 [1 2 3 4]]


Q. 9 Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

ANS)The array_split() method in NumPy is used to split an array into multiple sub-arrays. It is more flexible than the regular split() method because it can handle cases where the array cannot be evenly divided.

  Functionality:
    * The array_split() method divides an array into a specified number of equally or unequally sized sub-arrays.
    * If the array can't be divided evenly, it allows uneven splits by distributing the leftover elements into the earlier sub-arrays.

  Syntax:
   numpy.array_split(array, sections)
   where, array is the input array to be split and sections is the number of sub-arrays or a list of indices indicating where to split the array.
    
  How it Handles Uneven Splits -

   When the array size is not evenly divisible by the number of sections specified, array_split() divides the array as evenly as possible,
   giving larger sub-arrays at the start. If some leftover elements remain, the first few sub-arrays get one extra element each until all elements are distributed.

  Splitting 2D Arrays: array_split() can also split multi-dimensional arrays along a specific axis.

  Handling Uneven Splits in Multi-dimensional Arrays:
   If the number of rows (or columns, depending on the axis) is not evenly divisible, array_split() will distribute the extra rows/columns into earlier sub-arrays.

  Key Differences from split():
   The split() function raises a ValueError if the array cannot be split evenly.
   The array_split() method handles uneven splits gracefully by adjusting the sub-array sizes.


In [ ]:
#solitting 1 D array into 3 subarrays
arr = np.array([1,2,3,4,5,6,7])
result = np.array_split(arr, 3)
print("Array split int 3 sunarrays:\n", result)

# Splitting the array into 2 parts along the default axis (rows)
result_2d = np.array_split(arr_2d, 2)
print("2D Array Split into 2 sub-arrays:\n", result_2d)

#splitting into 4 parts using array_split()
arr = np.array([1,2,3,4,5,6,7])
result_uneven = np.array_split(arr, 4)
print("Uneven Split into 4 sub-arrays:\n", result_uneven)


Array split int 3 sunarrays:
 [array([1, 2, 3]), array([4, 5]), array([6, 7])]
2D Array Split into 2 sub-arrays:
 [array([[1, 2, 3]]), array([[4, 5, 6]])]
Uneven Split into 4 sub-arrays:
 [array([1, 2]), array([3, 4]), array([5, 6]), array([7])]


Q.10 Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

ANS) Vectorization and Broadcasting in NumPy are key concepts that contribute to efficient array operations, making computations faster and more concise. Here's an explanation of both:

1. Vectorization:

Definition: Vectorization refers to performing operations on entire arrays (or large chunks of them) without explicit loops. Instead of processing elements one by one, operations are applied to entire arrays at once.

Efficiency: It leverages low-level optimizations and compiled code to perform these operations quickly, making them much faster than traditional Python loops.



In [ ]:
# Example : elements wise addition

import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition (vectorized)
c = a + b
# printing the value of "c"
c  # Output: [5, 7, 9]


array([5, 7, 9])

2. Broadcasting :

Definition: Broadcasting refers to how NumPy handles arrays with different shapes during arithmetic operations. It "stretches" the smaller array along one or more axes to match the shape of the larger array, without actually copying data.

Efficiency: Broadcasting allows you to perform operations between arrays of different shapes without needing to manually replicate or resize them, reducing memory usage and improving performance.

Rules: Broadcasting works when dimensions of arrays are compatible, either:

The dimensions are equal.
One of the dimensions is 1 (allowing expansion).


In [ ]:
# Example: Adding a scalar to a 1D array:

a = np.array([1, 2, 3])

# Broadcasting the scalar 5 to each element in array 'a'
b = a + 5
print("The result is : ", b)  # Output: [6, 7, 8]


# Adding a 1D array to a 2D array:

x = np.array([[1, 2, 3],[4, 5, 6]])

y = np.array([10, 20, 30])

# Broadcasting y across each row of x
z = x + y
print("\nThe result is : \n",z)
# Output:
# [[11 22 33]
#  [14 25 36]]


The result is :  [6 7 8]

The result is : 
 [[11 22 33]
 [14 25 36]]


Contributions to Efficient Array Operations:

No explicit loops: Both vectorization and broadcasting eliminate the need for writing loops, which in Python can be slow. This results in more concise and readable code.

Memory efficiency: Broadcasting performs operations without creating unnecessary copies of arrays, leading to lower memory consumption.
Speed: Vectorized operations are optimized to use underlying C or Fortran libraries, making them significantly faster than element-wise Python loops.

# **PRACTICAL QUESTIONS**

Q.1 Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.


In [ ]:
# Ans

import numpy as np
# creating the array with random integers between 1 to 100
arr1 = np.random.randint(1 , 100 , (3,3))
print("The 3x3 array is:\n",arr1) # printing the array

# Interchanging the its rows and columns (Transposd array)
arr2 = arr1.T
print("The Transposed array is :\n", arr2)


The 3x3 array is:
 [[93 90 32]
 [79 60 98]
 [ 1 50 71]]
The Transposed array is :
 [[93 79  1]
 [90 60 50]
 [32 98 71]]


Q.2 Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.


In [ ]:
# Ans

arr1 = np.arange(10)
print("1D array:\n", arr1)

arr1_2x5 = arr1.reshape(2, 5)
print("\n Reshaped to 2x5 Array:\n", arr1_2x5)

arr1_5x2 = arr1.reshape(5, 2)
print("\n Reshaped to 5x2 Array:\n", arr1_5x2)

Q. 3 Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.


In [ ]:
# Ans :

import numpy as np
# Creating  a 4x4 array with random float values
arr = np.random.rand(4,4)
print("The 4x4 array with random float values: \n", arr)

# adding a border of 0s around it and making a 6x6 array
arr_6x6 = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("\nThe 6x6 array with 0s as borderd is:\n", arr_6x6)


The 4x4 array with random float values: 
 [[0.26749914 0.24204397 0.31216045 0.87997238]
 [0.23897328 0.54694454 0.80727559 0.27469063]
 [0.03665528 0.98544841 0.35069215 0.36378049]
 [0.744105   0.46585316 0.40983051 0.34158036]]

The 6x6 array with 0s as borderd is:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.26749914 0.24204397 0.31216045 0.87997238 0.        ]
 [0.         0.23897328 0.54694454 0.80727559 0.27469063 0.        ]
 [0.         0.03665528 0.98544841 0.35069215 0.36378049 0.        ]
 [0.         0.744105   0.46585316 0.40983051 0.34158036 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Q.4 Using NumPy, create an array of integers from 10 to 60 with a step of 5.


In [ ]:
# Ans

int_array = np.arange(10, 61, 5)
print(int_array)


[10 15 20 25 30 35 40 45 50 55 60]


Q.5 Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.


In [ ]:
#Ans

str_array = np.array(['python', 'numpy', 'pandas'])
print('Array of strings:', str_array)

print('\n Uppercase:', np.char.upper(str_array))
print('\n Lowercase:', np.char.lower(str_array))
print('\n Title case:', np.char.title(str_array))


Array of strings: ['python' 'numpy' 'pandas']

 Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']

 Lowercase: ['python' 'numpy' 'pandas']

 Title case: ['Python' 'Numpy' 'Pandas']


Q.6 Generate a NumPy array of words. Insert a space between each character of every word in the array.


In [ ]:
# Ans:
import numpy as np

# creating an array of some words
arr_word = np.array(["Ayesha","Abdullah", "Delusional", "World"])
print("The original  array is:", arr_word)

# inserting a space between every character
arr_space = np.char.join(" ",arr_word)
print("\nArray with space:\n",arr_space)


The original  array is: ['Ayesha' 'Abdullah' 'Delusional' 'World']

Array with space:
 ['A y e s h a' 'A b d u l l a h' 'D e l u s i o n a l' 'W o r l d']


Q.7 Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.


In [ ]:
# Ans :
import numpy as np

# creating two 3x3 numpy array with random value from 1-10
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,3))

# print the two array
print("Array_1 is:\n",arr1)
print("\nArray_2 is:\n",arr2)

# performing element wise operation
print("\n===Element wise operation===")

# Addition
add = arr1 + arr2
print("\nAddition:\n ", add)

# subtraction
sub = arr1 - arr2
print("\nSubtraction:\n", sub)

#multiplication
mult = arr1 * arr2
print("\nMultiplication:\n", mult)

# division
div = arr1 / arr2
print("\nDivision:\n",div)


Array_1 is:
 [[9 5 5]
 [5 5 1]]

Array_2 is:
 [[4 1 1]
 [6 7 2]]

===Element wise operation===

Addition:
  [[13  6  6]
 [11 12  3]]

Subtraction:
 [[ 5  4  4]
 [-1 -2 -1]]

Multiplication:
 [[36  5  5]
 [30 35  2]]

Division:
 [[2.25       5.         5.        ]
 [0.83333333 0.71428571 0.5       ]]


Q.8 Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.


In [ ]:
#Ans
identity_matrix = np.eye(5)
print('5x5 identity matrix:\n', identity_matrix)

diagonal_el = np.diag(identity_matrix)
print('\n Diagonal elements: \n', diagonal_el)


5x5 identity matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

 Diagonal elements: 
 [1. 1. 1. 1. 1.]


Q.9 Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.


In [ ]:
#Ans
random_int = np.random.randint(0, 1000, size = 100)
print('Random integers between 0 to 1000: \n', random_int)

def is_prime(number):
    if number < 2:
        return False
    for i in range(2, int(np.sqrt(number)) + 1):
        if number % i == 0:
            return False
        return True
prime_numbers = np.array([number for number in random_int if is_prime(number)])
print('\n Prime numbers in the array: \n', prime_numbers)


Random integers between 0 to 1000: 
 [365 543 704 504 918 226 251 131 776 277  24 196 189 880 107 975  89   7
 244 270 934  49 877 743 917 184 521 806 163 690 209 136  26  46 131 726
 129 556 224 276 805  65 497 488 996 680 691 283 835 325 370 917  29 914
 458 475 163 323 341 325 574 916 119 979 627 531 462 327 397 107 375 195
 383 470 440 636 872  79 100 868 689 233 814 986 546 451 534 805  86 765
 764 115 701 419 886 929 627 222 412 570]

 Prime numbers in the array: 
 [365 543 251 131 277 189 107 975  89   7  49 877 743 917 521 163 209 131
 129 805  65 497 691 283 835 325 917  29 475 163 323 341 325 119 979 627
 531 327 397 107 375 195 383  79 689 233 451 805 765 115 701 419 929 627]


Q.10 Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages


In [ ]:
# Ans :
import numpy as np

# generating a numpy aray of daily temprature for a month (temp range - 25 to 50)

daily_temp = np.random.randint(25, 55, size = 30)

print("Daily temp:\n", daily_temp)

#assuming 5 weeks of days each so reshaping the array
weekly_temp = daily_temp.reshape(5,6)
print("\nWeekly temp:\n", weekly_temp)

# calculating the  weekly averages

week_temp_avg = np.mean(weekly_temp,axis=1)
print("\nWeekly temperature avg :")
# week_temp_avg
for i in week_temp_avg:
    print("week avg temp",i ,"`C")


Daily temp:
 [25 52 37 52 26 50 51 49 31 46 45 43 36 28 50 29 32 48 42 37 28 30 27 38
 35 35 26 39 52 51]

Weekly temp:
 [[25 52 37 52 26 50]
 [51 49 31 46 45 43]
 [36 28 50 29 32 48]
 [42 37 28 30 27 38]
 [35 35 26 39 52 51]]

Weekly temperature avg :
week avg temp 40.333333333333336 `C
week avg temp 44.166666666666664 `C
week avg temp 37.166666666666664 `C
week avg temp 33.666666666666664 `C
week avg temp 39.666666666666664 `C
